
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amai
 */
public class frmClase13 extends javax.swing.JDialog {

          // Variable para las funciones propias
    Funciones  oFunc = new Funciones();
    /**
     * Creates new form frmClase13
     */
    public frmClase13(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         //Centro la Forma   
        this.setLocationRelativeTo(null);        
        this.setTitle("Reporte de Ventas por Forma de Pago");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblnombrearchivo = new javax.swing.JLabel();
        rbrespaldar = new javax.swing.JRadioButton();
        rbrestaurar = new javax.swing.JRadioButton();
        txtarchivo = new javax.swing.JTextField();
        txtseleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtresultados = new javax.swing.JTextArea();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblnombrearchivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnombrearchivo.setText("Nombre del Archivo para:");

        rbrespaldar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbrespaldar.setText("Respaldar");
        rbrespaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbrespaldarActionPerformed(evt);
            }
        });

        rbrestaurar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbrestaurar.setText("Restaurar");
        rbrestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbrestaurarActionPerformed(evt);
            }
        });

        txtseleccionar.setText("Seleccionar");
        txtseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseleccionarActionPerformed(evt);
            }
        });

        txtresultados.setColumns(20);
        txtresultados.setRows(5);
        jScrollPane1.setViewportView(txtresultados);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblnombrearchivo)
                                        .addGap(129, 129, 129)
                                        .addComponent(rbrespaldar))
                                    .addComponent(txtarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtseleccionar)
                                    .addComponent(rbrestaurar)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombrearchivo)
                    .addComponent(rbrespaldar)
                    .addComponent(rbrestaurar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtseleccionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
         String sCadena="";
        
        // Valida que haya algún nombre de archivo
        if (txtarchivo.getText().length()>7)
        {
            // Inicializa el area de texto
            txtresultados.setText("");
            
            // Verifica acción a ejecutar
            if (rbrespaldar.isSelected())
            {
                // Ejecuta el Comando para crear el respaldo
                sbEjecutaComando("cmd /c respalda.bat "+ txtarchivo.getText().toString());
                
                try 
                {
                    BufferedReader bf = new BufferedReader(new FileReader(txtarchivo.getText().toString()));
                    try {
                        while ((sCadena = bf.readLine())!=null) 
                        {
                            //System.out.println(sCadena);
                            txtresultados.setText(txtresultados.getText()+sCadena+"\n");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(frmClase13.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
                catch (FileNotFoundException ex) 
                {
                    Logger.getLogger(frmClase13.class.getName()).log(Level.SEVERE, null, ex);
                }    
            }
            else
            {
                // Ejecuta el Comando para crear el respaldo
                sbEjecutaComando("cmd /c restaura.bat "+txtarchivo.getText().toString());
                
            }
                
        }
        else
            oFunc.SubSistemaMensaje("Debe Capturar el Nombre del Archivo mayor de 7 caracteres");
        
            
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
         // Acepta la Venta
        Globales.bVentaRealizada = false;

        // Cierra la Forma
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseleccionarActionPerformed
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
        int iResult = fileChooser.showOpenDialog(null);
        if (iResult == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            txtarchivo.setText(file.toString());
        }
    }//GEN-LAST:event_txtseleccionarActionPerformed

    private void rbrespaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbrespaldarActionPerformed
        // TODO add your handling code here:
         rbrestaurar.setSelected(! rbrespaldar.isSelected());
    }//GEN-LAST:event_rbrespaldarActionPerformed

    private void rbrestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbrestaurarActionPerformed
        // TODO add your handling code here:
         rbrespaldar.setSelected(! rbrestaurar.isSelected());
    }//GEN-LAST:event_rbrestaurarActionPerformed
    
     private void SbLoadInformation(String v)
    {
        //javax.swing.JOptionPane.showMessageDialog(null, v, "Avisador",javax.swing.JOptionPane.PLAIN_MESSAGE );
        
        txtresultados.setText(txtresultados.getText()+v+"\n");
    }
     
      private void sbEjecutaComando(String pcmd)
    {
        try
        {
            // Variable para Ejecutar el Proceso
            Process cmd = Runtime.getRuntime().exec(pcmd);
            
            // Espera a que termine el proceso
            cmd.waitFor();
            /*
            System.out.println(cmd.getOutputStream().toString());
            System.out.println(cmd.getInputStream().toString());
            System.out.println(cmd.getErrorStream().toString());
            */ 
            // Buffer para obtener la respuesta del Comando
            BufferedReader buf=new BufferedReader(new InputStreamReader(cmd.getInputStream()));
            String linea="";
            while ((linea=buf.readLine())!=null){
                System.out.println(linea);
                SbLoadInformation(linea.toString());
            } //fin while
            
            // Buffer para obtener la respuesta del Comando   
            BufferedReader buf2=new BufferedReader(new InputStreamReader(cmd.getErrorStream()));
            String linea2="";
            while ((linea2=buf2.readLine())!=null){
                System.out.println(linea2);
                SbLoadInformation(linea2.toString());
            } //fin while
            
        } //fin try
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(null, e, "Excepcion",javax.swing.JOptionPane.PLAIN_MESSAGE );
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClase13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClase13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClase13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClase13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmClase13 dialog = new frmClase13(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblnombrearchivo;
    private javax.swing.JRadioButton rbrespaldar;
    private javax.swing.JRadioButton rbrestaurar;
    private javax.swing.JTextField txtarchivo;
    private javax.swing.JTextArea txtresultados;
    private javax.swing.JButton txtseleccionar;
    // End of variables declaration//GEN-END:variables
}
